---
  type: "list_quat"
  diag: true
  min_dist: 0.5
  goals:
     # x,  y,    z, qx, qy, qz, qw,  u,  v,  w,  p,  q,  r
    - [5., 0., -50., 0., 0., 0., 1., 0., 0., 0., 0., 0.]
    - [5., 5., -50., 0., 0., 0., 1., 0., 0., 0., 0., 0.]
    - [0., 5., -50., 0., 0., 0., 1., 0., 0., 0., 0., 0.]
    - [0., 0., -50., 0., 0., 0., 1., 0., 0., 0., 0., 0.]
  Q:
    - 1000.0 # x
    - 1000.0 # y
    - 1000.0 # z
    - 10000.0 # angle
    - .0 # u
    - .0 # v
    - .0 # w
    - .0 # p
    - .0 # q
    - 10.0 # r